
[params]
  [params.minimalanalytics]
    # GA4 analytics Tracking ID.
    tracking_id = "G-ABCDEFGHIJ"

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.imports]]
    path = "github.com/jahilldev/minimal-analytics"
    [[module.imports.mounts]]
      source = "packages/ga4/src"
      target = "assets/js/ga4"
    [[module.imports.mounts]]
      source = "packages/shared/src"
      target = "assets/js/ga4-shared"
